# Site settings
title: "Home"
description: "Insights and experiences in Magento development, performance optimization, and more."
url: "https://balvesh.github.io/"
baseurl: "/blog" # the subpath of your site, e.g. /blog

# Author settings
author:
  name: "Balvesh Rakkar"
  email: "balveshr@gmail.com"
  twitter_username: BalveshS
  github_username: balvesh

# Theme settings
theme: minima

# Minima theme settings
minima:
  accent_color: "#ff5f57"
  background_color: "#1c1e26"
  heading_color: "#f8f8f2"
  text_color: "#a6accd"
  link_color: "#8be9fd"
  sidebar:
    pinned: true
    social_links:
      twitter: https://twitter.com/BalveshS
      github: https://github.com/balvesh
      linkedin: https://www.linkedin.com/in/balvesh-rakkar/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Pagination
paginate: 5
paginate_path: "/page/:num/"

# Permalinks
permalink: /:categories/:year/:month/:day/:title.html
