# Site settings
title: "Balvesh Rakkar's Dev Blog"
description: "Insights and experiences in Magento development, performance optimization, and more."
url: "https://balvesh.github.io/"
baseurl: "/blog" # the subpath of your site, e.g. /blog

# Author settings
author:
  name: "Balvesh Rakkar"
  email: "balveshr@gmail.com"
  twitter_username: BalveshS
  github_username: balvesh

# Theme settings
theme: minima

# Minima theme settings
minima:
  accent_color: "#2d4f7c"
  background_color: "#ffffff"
  heading_color: "#1a202c"
  text_color: "#4a5568"
  link_color: "#2b6cb0"
  sidebar:
    pinned: true
    social_links:
      twitter: https://twitter.com/BalveshS
      github: https://github.com/balvesh
      linkedin: https://www.linkedin.com/in/balvesh-rakkar/

######################################
# --- Colours / background image --- #
######################################

# Personalize the colours in your website. Colour values can be any valid CSS colour

page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

# Alternatively, the navbar, footer, and page background can be set to an image
# instead of colour

#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

# Suggest a colour for mobile browsers to use as the browser's theme. This is only supported by a few mobile browsers.
#mobile-theme-col: "#0085A1"

# For any extra visual customization, you can include additional CSS files in every page on your site. List any custom CSS files here
#site-css:
#  - "/assets/css/custom-styles.css"

# If you have common JavaScript files that should be included in every page, list them here
#site-js:
#  - "/assets/js/custom-script.js"


# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Pagination
paginate: 5
paginate_path: "/page/:num/"

# SEO and social sharing
social:
  name: "Balvesh Rakkar"
  description: "Lead Developer at Rightpoint | Magento Expert | Performance Optimization Enthusiast"
  links:
    - "https://twitter.com/BalveshS"
    - "https://github.com/balvesh"
    - "https://www.linkedin.com/in/balvesh-rakkar/"
  image: "/assets/images/profile.jpg"



# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title.html
