# Site settings
title: "Home"
description: "Insights and experiences in Magento development, performance optimization, and more..."
url: "https://balvesh.github.io/"
baseurl: "/blog" # the subpath of your site, e.g. /blog

# Author settings
author:
  name: "Balvesh Rakkar"
  email: "balveshr@gmail.com"
  twitter_username: BalveshS
  github_username: balvesh

# Theme settings
theme: minima

# Minima theme settings
minima:
  custom_css: /assets/css/style.scss

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Pagination
paginate: 5
paginate_path: "/page/:num/"

# Permalinks
permalink: /:categories/:year/:month/:day/:title.html
